version: '3.8'
services:
  python-container:
    image: python:latest
    volumes:
      - .:/codigo
    working_dir: /codigo
    entrypoint: ["bash", "-c"]

  java-container:
    image: openjdk:latest
    volumes:
      - .:/codigo
    working_dir: /codigo
    entrypoint: ["bash", "-c"]

  cpp-container:
    image: gcc:latest
    volumes:
      - .:/codigo
    working_dir: /codigo
    entrypoint: ["bash", "-c"]

  js-container:
    image: node:latest
    volumes:
      - .:/codigo
    working_dir: /codigo
    entrypoint: ["bash", "-c"]

  ruby-container:
    image: ruby:latest
    volumes:
      - .:/codigo
    working_dir: /codigo
    entrypoint: ["bash", "-c"]
